name                   'pmsiplan'
maintainer             'jubianchi'
maintainer_email       'contact@jubianchi.fr'
license                'proprietary'
description            'Installs/Configures PMSIplan'
version                '0.1.0'

depends                'apt'
depends                'apache2'
depends                'mongodb'
depends                'nodejs'
depends                'npm'
